server:
  port: 7080

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/

spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/inst02
    username: root
    password: zwjhuhu
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
#  data:
#    mongodb:
#      uri: mongodb://10.37.147.250:27017,10.37.147.250:27017
#  cloud:
#    zookeeper:
#      connectString: 127.0.0.1:2181


ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 15000
  MaxAutoRetries: 0

mybatis:
  type-aliases-package: com.bytesvc.consumer.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
