server:
  port: 7070

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/


spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/inst01
    username: root
    password: zwjhuhu
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
#  data:
#    mongodb:
#      uri: mongodb://10.37.147.250:27017/bytetcc
#  cloud:
#    zookeeper:
#      connectString: 127.0.0.1:2181
